/* Generated By:JavaCC: Do not edit this line. GParserConstants.java */
package grammar;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 9;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 10;
  /** RegularExpression Id. */
  int LPAREN = 12;
  /** RegularExpression Id. */
  int RPAREN = 13;
  /** RegularExpression Id. */
  int LBRACE = 14;
  /** RegularExpression Id. */
  int RBRACE = 15;
  /** RegularExpression Id. */
  int SEMI = 16;
  /** RegularExpression Id. */
  int COLON = 17;
  /** RegularExpression Id. */
  int DOT = 18;
  /** RegularExpression Id. */
  int COMMA = 19;
  /** RegularExpression Id. */
  int QUOTE = 20;
  /** RegularExpression Id. */
  int EQ = 21;
  /** RegularExpression Id. */
  int COLONEQEQ = 22;
  /** RegularExpression Id. */
  int COLONEQ = 23;
  /** RegularExpression Id. */
  int STAR = 24;
  /** RegularExpression Id. */
  int PLUS = 25;
  /** RegularExpression Id. */
  int QUES = 26;
  /** RegularExpression Id. */
  int XOR = 27;
  /** RegularExpression Id. */
  int TILDE = 28;
  /** RegularExpression Id. */
  int HASH = 29;
  /** RegularExpression Id. */
  int KEYWORD_TOKEN = 30;
  /** RegularExpression Id. */
  int KEYWORD_TOKENS = 31;
  /** RegularExpression Id. */
  int KEYWORD_SKIP = 32;
  /** RegularExpression Id. */
  int STRING_LITERAL = 33;
  /** RegularExpression Id. */
  int INCLUDE_DIRECTIVE = 34;
  /** RegularExpression Id. */
  int START_SIRECTIVE = 35;
  /** RegularExpression Id. */
  int IDENT = 36;
  /** RegularExpression Id. */
  int CHAR = 37;
  /** RegularExpression Id. */
  int BRACKET_LIST = 38;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "\"//\"",
    "<token of kind 6>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 11>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\":\"",
    "\".\"",
    "\",\"",
    "\"\\\'\"",
    "\"=\"",
    "\":==\"",
    "\":=\"",
    "\"*\"",
    "\"+\"",
    "\"?\"",
    "\"^\"",
    "\"~\"",
    "\"#\"",
    "\"token\"",
    "\"tokens\"",
    "\"skip\"",
    "<STRING_LITERAL>",
    "\"include\"",
    "\"@start\"",
    "<IDENT>",
    "<CHAR>",
    "<BRACKET_LIST>",
    "\"|\"",
  };

}
