package mesut.parserx.parser;

public class Tokens {
    public static final int EOF = 0;
    public static final int BOOLEAN = 1;
    public static final int OPTIONS = 2;
    public static final int TOKEN = 3;
    public static final int INCLUDE = 4;
    public static final int START = 5;
    public static final int EPSILON = 6;
    public static final int LEFT = 7;
    public static final int RIGHT = 8;
    public static final int IDENT = 9;
    public static final int CALL_BEGIN = 10;
    public static final int SHORTCUT = 11;
    public static final int BRACKET = 12;
    public static final int STRING = 13;
    public static final int CHAR = 14;
    public static final int NUMBER = 15;
    public static final int LP = 16;
    public static final int RP = 17;
    public static final int LBRACE = 18;
    public static final int RBRACE = 19;
    public static final int STAR = 20;
    public static final int PLUS = 21;
    public static final int QUES = 22;
    public static final int SEPARATOR = 23;
    public static final int TILDE = 24;
    public static final int HASH = 25;
    public static final int COMMA = 26;
    public static final int OR = 27;
    public static final int DOT = 28;
    public static final int SEMI = 29;
    public static final int ARROW = 30;
    public static final int EQ = 31;
    public static final int MINUS = 32;
    public static final int LINE_COMMENT = 33;
    public static final int BLOCK_COMMENT = 34;
    public static final int WS = 35;
    public static final int ACTION = 36;
    public static final int LEXER_MEMBERS_BEGIN = 37;
    public static final int WS1 = 38;
    public static final int LEXER_MEMBER = 39;
    public static final int MEMBERS_END = 40;
}
