
//----------------------------------------------------
// The following code was generated by jh-javacup-1.0 20160720
// Fri Mar 27 08:47:08 UTC 2020
//----------------------------------------------------

package grammar;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 0;
  public static final int EOF = 1;
  public static final int STAR = 2;
  public static final int PLUS = 3;
  public static final int QUES = 4;
  public static final int OR = 5;
  public static final int SEMI = 6;
  public static final int COLON = 7;
  public static final int COMMA = 8;
  public static final int EQ = 9;
  public static final int LPAREN = 10;
  public static final int RPAREN = 11;
  public static final int TOKEN = 12;
  public static final int IDENT = 13;
}

